apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager  # Or whatever namespace you want
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-staging  # Use staging first to test
    kind: ClusterIssuer
  dnsNames:
  - "*.lab2.tailandtraillabs.com"  # Change to your subdomain
  - "lab2.tailandtraillabs.com"    # Optional: include the base subdomain too