
  #volumes:
  #nfs_dataz:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: "nolock,hard,rw,noatime"
  #    device: "danas.hangar.bpfx.org:/volume1/dataz/"

services:
  prowlarr:
    container_name: prowlarr
    #image: cr.hotio.dev/hotio/sonarr:release
    image: ghcr.io/hotio/prowlarr:release
    ports:
      - "9696:9696"
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - HAS_IPV6=false
    volumes:
      - /data/containers/prowlarr/config:/config
      - /danas/dataz/Media:/data
    restart: always

  sonarr:
    container_name: sonarr
    #image: cr.hotio.dev/hotio/sonarr:release
    image: ghcr.io/hotio/sonarr:release
    ports:
      - "8989:8989"
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - HAS_IPV6=false
    volumes:
      - /data/containers/sonarr/config:/config
      - /danas/dataz/Media:/data
    restart: always

#`  nzbget:
#`  container_name: nzbget
#  #image: cr.hotio.dev/hotio/nzbget:release
#    image: lscr.io/linuxserver/nzbget
#    ports:
#      - "6789:6789"
#    environment:
#      - TZ=America/Chicago
#      - PUID=1000
#      - PGID=1000
#      - UMASK=002
#    volumes:
#      - /data/nzbget/config:/config
#      - /data/nzbget/main:/main
#      - /danas:/data
#    network:
#      main:
#        alias:
#          - nzbget
#    restart: always

  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd
    ports: 
      - 8080:8080
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - HAS_IPV6=false
    volumes:
      - /data/containers/sabnzbd/config:/config
      - /data/containers/sabnzbd/main:/main
      - /danas/dataz/Media:/data
    restart: unless-stopped


  radarr:
    #image: cr.hotio.dev/hotio/radarr:release
    image: ghcr.io/hotio/radarr:release
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - HAS_IPV6=false
    volumes:
      - /data/containers/radarr/config:/config
      - /danas/dataz/Media:/data
    restart: on-failure

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - HAS_IPV6=false
    volumes:
      - /data/containers/bazarr/config:/config
      - /danas/dataz/Media:/data
    restart: always
