#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <gfind_icons.h>

int32_t gfind_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm gfind!");

    return 0;
}
